version: "3.8"
services:
  fastapi:
    restart: unless-stopped
    build: .
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - .:/code
    depends_on:
      - mongo
      - kafka
    entrypoint: /code/entrypoint.sh
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./data:/data/db

  kafka:
    image: bitnami/kafka
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=${KAFKA_ADVERTISED_HOST_NAME}
      - KAFKA_CREATE_TOPICS=${KAFKA_CREATE_TOPICS}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
      - ALLOW_PLAINTEXT_LISTENER=${ALLOW_PLAINTEXT_LISTENER}

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "${ZOOKEEPER_PORT}:2181"
